CREATE TABLE inventory_log (
    log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    inventory_id NUMBER,
    store_id NUMBER,
    product_id NUMBER,
    change_amount NUMBER,
    old_quantity NUMBER,
    new_quantity NUMBER,
    action VARCHAR2(20), -- e.g. 'ADD', 'UPDATE', 'DELETE'
    changed_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    changed_by VARCHAR2(100) -- kullanıcı bilgisi, opsiyonel
);
/
CREATE TABLE audit_log (
  log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  table_name VARCHAR2(100),
  operation VARCHAR2(10),
  changed_by VARCHAR2(100),
  changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  old_data CLOB,
  new_data CLOB
);
/