CREATE TABLE inventory_log (
    log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    inventory_id NUMBER,
    store_id NUMBER,
    product_id NUMBER,
    change_amount NUMBER,
    old_quantity NUMBER,
    new_quantity NUMBER,
    action VARCHAR2(20), -- e.g. 'ADD', 'UPDATE', 'DELETE'
    changed_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    changed_by VARCHAR2(100) -- kullanıcı bilgisi, opsiyonel
);
/